#!/usr/bin/env bash
# install nginx and add html file
sudo apt-get -y install nginx;sudo touch /var/www/html/index.html echo "Hello World!" | sudo tee -a /var/www/html/index.html;printf %s "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /var/www/html;
  index index.html
}" > /etc/nginx/sites-available/default

sudo service nginx restart
