#!/usr/bin/env bash
# install nginx and add html file
sudo apt-get -y install nginx;mkdir /etc/nginx/html;echo "Hello World!" > /etc/nginx/html/index.html;printf %s "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /etc/nginx/html;
  index index.html;
}" > /etc/nginx/sites-available/default

sudo service nginx restart
