#!/usr/bin/env bash
# Redirection 
sudo apt-get update -y;
sudo apt-get install -y nginx;
sudo mkdir /etc/nginx/html;
sudo touch /etc/nginx/html/index.html;
echo "Hello World!" >> /etc/nginx/html/index.html;
printf %s "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /etc/nginx/html;
  index index.html;

  location /redirect_me {
    return 301 https://i.imgur.com/guDXtsC.png;
  }
}
" > /etc/nginx/sites-available/default;
sudo service nginx restart
