#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user.
sudo pkill apache2
sudo chmod 664 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
