#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user.
chmod 777 /etc/nginx/nginx.conf;
pkill apache2;
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default;
sudo service nginx restart
