#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user.
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default;
sudo sed -i 's/www-data/nginx/g' /etc/nginx/nginx.conf;
sudo service nginx restart
