#!/usr/bin/env bash
#short and sweet
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
